-- AlterTable
ALTER TABLE "User" ADD COLUMN "isMuted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "mutedUntil" DATETIME;
ALTER TABLE "User" ADD COLUMN "muteReason" TEXT;
ALTER TABLE "User" ADD COLUMN "mutedAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "mutedBy" TEXT;